### Estado global del sistema
GET http://127.0.0.1:8000/vx11/status

### Estado de Madre
POST http://127.0.0.1:8000/vx11/action/control
Content-Type: application/json

{
  "target": "madre",
  "action": "status"
}
