#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# VX11 Automation Pipeline - Reproducible Core Testing
#
# Contract:
# 1. Start common services (non-interactive)
# 2. Run checks (scripts/run_checks.sh)
# 3. Generate scorecard (scripts/generate_scorecard.py)
# 4. Stop non-madre EXCEPT tentaculo_link (preserve single entrypoint)
# 5. Generate summary in docs/status (tracked) + evidence in docs/audit (untracked)
#
# Exit: 0 if all steps pass, logs to docs/audit/<TS>/automation_run.log
###############################################################################

TS=$(date -u +"%Y%m%dT%H%M%SZ")
OUT="docs/audit/$TS"
STATUS_FILE="docs/status/last_automation_run.md"

mkdir -p "$OUT"
mkdir -p "docs/status"

# Ensure both stdout and log file get all output
{
    echo "=== VX11 Automation Pipeline ===" 
    echo "Timestamp: $TS"
    echo "Profile: ${VX11_PROFILE:-test}"
    echo ""
    
    echo "1) Starting services..."
    ./scripts/start_services.sh || true
    
    echo "Waiting 8s for services to initialize..."
    sleep 8
    
    echo "2) Running checks..."
    ./scripts/run_checks.sh || true
    
    echo "3) Generating scorecard..."
    python3 scripts/generate_scorecard.py || true
    
    echo "4) Stopping non-madre services (EXCEPT tentaculo_link)..."
    # Custom stop: stop all EXCEPT madre AND tentaculo_link
    ALL=$(docker compose -f docker-compose.full-test.yml ps --services 2>/dev/null || true)
    for s in $ALL; do
        if [ "$s" != "madre" ] && [ "$s" != "tentaculo_link" ] && [ "$s" != "redis-test" ]; then
            echo "  Stopping $s..."
            docker compose -f docker-compose.full-test.yml stop "$s" 2>&1 || true
        fi
    done
    
    echo "Final service state:"
    docker compose -f docker-compose.full-test.yml ps
    
    echo ""
    echo "Automation run complete; evidence in $OUT"
    echo "Summary: $STATUS_FILE"
    
} | tee "$OUT/automation_run.log"

###############################################################################
# Generate tracked summary (no secrets, only state)
###############################################################################
cat > "$STATUS_FILE" << EOF
# VX11 Last Automation Run

**Timestamp**: $TS
**Git HEAD**: $(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
**Profile**: ${VX11_PROFILE:-test}

## Status
- Core running: madre + tentaculo_link + redis-test
- Operator: Available via http://localhost:8000/operator/ui
- Auth: X-VX11-Token (vx11-test-token)

## Evidence Location
Full logs: docs/audit/$TS/

## Next Steps
\`\`\`bash
# Access operator UI
curl -s http://localhost:8000/operator/ui

# Test operator API
curl -H "X-VX11-Token: vx11-test-token" \\
  http://localhost:8000/operator/api/health

# Check events stream
curl -H "X-VX11-Token: vx11-test-token" \\
  http://localhost:8000/operator/api/events?follow=true
\`\`\`

---
Generated by automation_full_run.sh
EOF

echo "[automation] Summary written to $STATUS_FILE"
echo "$OUT"
