#!/usr/bin/env python3
"""
Clasifica procesos del sistema en CANONICAL / STALE / ZOMBIE_REAL.
Lee el listado en tiempo real usando ps y genera Markdown en docs/archive/SYSTEM_PROCESS_CLASSIFICATION.md
"""
from scripts.cleanup_guard import safe_move_py, safe_rm_py

import subprocess
from pathlib import Path
import shlex

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "archive" / "SYSTEM_PROCESS_CLASSIFICATION.md"
OUT.parent.mkdir(parents=True, exist_ok=True)

KEYWORDS_CANONICAL = [
    "vx11",
    "docker",
    "containerd",
    "dockerd",
    "sshd",
    "ssh",
    "dbus",
    "systemd",
    "NetworkManager",
    "nm",
    "dbus-daemon",
    "container",
    "kube",
    "podman",
]

rows = []
counts = {"CANONICAL": 0, "STALE": 0, "ZOMBIE_REAL": 0}

# Get process list
ps_out = subprocess.check_output(
    ["ps", "-eo", "pid,ppid,stat,user,comm,args"], text=True
)
lines = ps_out.strip().splitlines()
# skip header
for line in lines[1:]:
    parts = line.strip().split(None, 5)
    if len(parts) < 6:
        continue
    pid, ppid, stat, user, comm, args = parts
    classification = "CANONICAL"
    reason = "Default canonical"
    stat_flags = stat
    lower_args = args.lower()
    lower_comm = comm.lower()
    # Zombies
    if "Z" in stat_flags:
        # parent
        try:
            ppid_int = int(ppid)
            parent_comm = subprocess.check_output(
                ["ps", "-p", str(ppid_int), "-o", "comm="], text=True
            ).strip()
        except Exception:
            parent_comm = ""
        if ppid_int != 1 and "systemd" not in parent_comm.lower():
            classification = "ZOMBIE_REAL"
            reason = f"STAT=Z and parent ({ppid_int}:{parent_comm}) not systemd"
            counts["ZOMBIE_REAL"] += 1
            rows.append((pid, ppid, stat, user, comm, args, classification, reason))
            continue
        else:
            classification = "CANONICAL"
            reason = f"STAT=Z but parent is systemd or pid 1 ({ppid}:{parent_comm})"
    # Canonical keywords
    if any(k in lower_args or k in lower_comm for k in KEYWORDS_CANONICAL):
        classification = "CANONICAL"
        reason = "Matches canonical keyword"
    # Python / uvicorn heuristics
    elif "python" in lower_comm or "python" in lower_args or "uvicorn" in lower_args:
        # check cgroup for docker
        cgroup_path = Path(f"/proc/{pid}/cgroup")
        in_container = False
        try:
            if cgroup_path.exists():
                cg = cgroup_path.read_text()
                if "docker" in cg or "kubepods" in cg or "containerd" in cg:
                    in_container = True
        except Exception:
            pass
        if in_container:
            classification = "CANONICAL"
            reason = "Python inside container"
        elif "vx11" in lower_args or "/home" in lower_args and "vx11" in lower_args:
            classification = "CANONICAL"
            reason = "Python process belongs to vx11 tree"
        else:
            classification = "STALE"
            reason = "Orphan python/uvicorn without container or vx11 path"
            counts["STALE"] += 1
    else:
        classification = "CANONICAL"
        reason = "Conservative default: system/important process"
    counts.setdefault(classification, 0)
    counts[classification] += 1
    rows.append((pid, ppid, stat, user, comm, args, classification, reason))

# write markdown
with OUT.open("w", encoding="utf-8") as f:
    f.write("# System Process Classification\n\n")
    f.write(
        "Generated by `scripts/system_classify.py`. Classification is heuristic and conservative.\n\n"
    )
    f.write("## Counts\n\n")
    for k in ["CANONICAL", "STALE", "ZOMBIE_REAL"]:
        f.write(f"- {k}: {counts.get(k,0)}\n")
    f.write("\n## Table\n\n")
    f.write("| pid | ppid | stat | user | comm | args | classification | reason |\n")
    f.write("|---|---|---|---|---|---|---|---|\n")
    for r in rows:
        pid, ppid, stat, user, comm, args, classification, reason = r
        safe_args = args.replace("|", "\|")[:200]
        f.write(
            f"| {pid} | {ppid} | {stat} | {user} | {comm} | {safe_args} | {classification} | {reason} |\n"
        )

print("Wrote", OUT)