"""
Pydantic models for INEE Extended: Builder, Colony, Rewards, Manifestator.
All dormant until feature flags enabled.
"""

from pydantic import BaseModel
from typing import Optional, Dict, Any, List
from datetime import datetime
import json


# ============ BUILDER MODELS ============


class BuilderSpec(BaseModel):
    """Patchset specification (template)."""

    spec_id: str
    module_name: str
    patch_type: str  # code|config|schema|diagnostic
    description: Optional[str] = None
    parameters: Optional[Dict[str, Any]] = None

    class Config:
        json_schema_extra = {
            "example": {
                "spec_id": "spec-001",
                "module_name": "switch",
                "patch_type": "config",
                "description": "Add new routing rule",
                "parameters": {"rule_type": "adaptive"},
            }
        }


class BuilderPatchset(BaseModel):
    """Generated patchset (from spec, before execution)."""

    patchset_id: str
    builder_spec_id: str
    intent_id: Optional[str] = None
    changes_json: str  # JSON-stringified patch details
    status: str = "generated"  # generated|pending_approval|approved|rejected|applied
    created_at: datetime


class BuilderPromptPack(BaseModel):
    """Prompt pack generated by builder."""

    pack_id: str
    patchset_id: Optional[str] = None
    prompts: List[str]  # Actual prompts for LLM
    context: Optional[Dict[str, Any]] = None
    created_at: datetime


class BuilderCreatePatchsetRequest(BaseModel):
    """Request to Builder: create patchset (does NOT execute)."""

    spec_id: str
    description: Optional[str] = None
    parameters: Optional[Dict[str, Any]] = None
    create_intent: bool = True  # If True, create INTENT for Spawner

    class Config:
        json_schema_extra = {
            "example": {
                "spec_id": "spec-001",
                "description": "Fix routing bug in switch",
                "create_intent": True,
            }
        }


# ============ COLONY MODELS ============


class ColonyEnvelope(BaseModel):
    """HMAC-signed envelope for remote colony communication."""

    envelope_id: str
    colony_id: str
    nonce: str  # Unique per message (for replay protection)
    hmac_signature: str  # HMAC-SHA256
    payload_json: str
    created_at: datetime


class ColonyLifecycleState(BaseModel):
    """Colony state machine: egg -> larva -> adult."""

    colony_id: str
    state: str  # egg|larva|adult
    state_changed_at: datetime
    heartbeat_at: Optional[datetime] = None
    ack_count: int = 0
    retry_count: int = 0
    metadata: Optional[Dict[str, Any]] = None


class ColonyRegisterRequest(BaseModel):
    """Register new remote colony."""

    colony_id: str
    remote_url: Optional[str] = None  # Only if external INEE plane enabled
    metadata: Optional[Dict[str, Any]] = None

    class Config:
        json_schema_extra = {
            "example": {
                "colony_id": "colony-alpha",
                "remote_url": "https://inee-remote.example.com",
                "metadata": {"version": "1.0"},
            }
        }


class ColonyHeartbeat(BaseModel):
    """Colony heartbeat (keep-alive)."""

    colony_id: str
    timestamp: datetime
    status: str = "alive"


# ============ REWARD MODELS ============


class RewardAccount(BaseModel):
    """Reward account for agent/colony."""

    account_id: str
    account_type: str  # agent|colony|service
    balance_points: int = 0
    rank: str = "novice"  # novice|skilled|expert|master
    created_at: datetime


class RewardTransaction(BaseModel):
    """Reward transaction (debit/credit)."""

    transaction_id: str
    account_id: str
    amount_points: int
    reason: str  # task_completed|bugfix|optimization|exploration
    related_intent_id: Optional[str] = None
    created_at: datetime


class RewardScoring(BaseModel):
    """Scoring calculation for reward distribution."""

    scoring_id: str
    account_id: str
    task_complexity: int  # 1-10
    success_rate: float  # 0.0-1.0
    speed_multiplier: float
    points_earned: int
    scoring_date: datetime


class RewardStatusResponse(BaseModel):
    """Status of rewards engine."""

    status: str  # ok|disabled|error
    top_accounts: List[RewardAccount] = []
    total_points_in_circulation: int = 0


# ============ MANIFESTATOR EXTENDED MODELS ============


class ManifestatorPatchPlan(BaseModel):
    """Patch plan generated by Manifestator."""

    plan_id: str
    patch_type: str  # code|config|schema
    modules_affected: List[str]
    changes_summary: str
    risk_level: str  # low|medium|high
    estimated_impact: Dict[str, Any]


class ManifestatorPromptPack(BaseModel):
    """Prompt pack generated by Manifestator."""

    pack_id: str
    prompts: List[str]
    context: Optional[Dict[str, Any]] = None
    model_hint: Optional[str] = None


# ============ INEE INTENT (existing, but extended) ============


class INEEIntentRequest(BaseModel):
    """INEE intent submission (via Builder or external)."""

    intent_type: str  # diagnose|propose|apply
    payload: Dict[str, Any]
    remote_colony_id: Optional[str] = None
    correlation_id: Optional[str] = None


class INEEIntentResponse(BaseModel):
    """Response to INEE intent."""

    status: str
    intent_id: str
    correlation_id: Optional[str] = None
    operation: Optional[str] = None
    message: str


# ============ STATUS/HEALTH MODELS ============


class INEEStatusResponse(BaseModel):
    """INEE module status."""

    status: str  # ok|disabled|error
    enabled: bool
    remote_plane_enabled: bool
    execution_enabled: bool
    colonies_count: int = 0
    pending_intents: int = 0
    builder_available: bool = False
    rewards_available: bool = False
